---
title: "Dose Response Example"
---


import libraries 
```{r include=FALSE}
rm(list=ls())

library(dplyr)
library(drc)
library(readr)
library(here)
library(readxl)

```

# Helper Functions 
```{r}
geom_mean <- function(x) {
  exp(mean(log(x)))
}

drop_empties <- function(df) {
  df <- df %>% select_if(function(x) !(all(is.na(x)) | all(x == "") | all(x == "NR")))
  return(df)
}

cas_to_numeric <- function(df) {
  df <- df %>%
    mutate_if(is.integer64, as.numeric)
  return(df)
}

# use this to select the columns we care about 
relevant_cols <- function(df) {
  return(df %>%
    dplyr::select(
      any_of(
        c(
          "test_id",
          "reference_number",
          "chemical_name",
          "Chemical_name",
          "test_cas",
          "species_number",
          "organism_habitat",
          "exposure_type",
          "control_type",
          "media_type",
          "genus",
          "common_name",
          "latin_name",
          "species",
          "ecotox_group",
          "obs_duration_mean",
          "obs_duration_unit",
          "endpoint",
          "effect",
          "measurement",
          "conc1_mean",
          "conc1_unit",
          "conversion_factors",
          "conc_ug_L",
          "taxonomic.distance",
          "r", "R2", "intercept", "slope", "MSE",
          "endpoint_type", "US-EPA New Chemical Categories", "CAS", "ASTER",
          "chemical_name",
          "ecotox_group",
          "dtxsid", "epaName", "formatted_cas"
        )
      )
    ))
}
```


# Get and prepare data 
```{r}

tests.df <- read_rds(here('data','ecotox_mort_tests.rds'))

endpoint_classifications <- read_excel(here("xlsx","endpoint_classifications.xlsx")) %>% 
  dplyr::select(c(endpoint,endpoint_type = Type,percent_val)) %>% filter(endpoint_type != "out")

ecotox_tax_distance <- read_rds(here('data','salmonid_tax_distance.rds'))

chemicals <- read_rds(here('data','selected_chemical_info.rds'))

```

# Convert Units 
```{r}

# Original data
unit_names <- c(
  "ug/L", "ppm", "mg/L", "AI ug/L", "ppb",
  "AI ppb", "mmol/L", "AI ppm", "ng/L", "mg/kg bdwt",
  "mg/kg", "uM", "AI mg/L", "ul/L", "ug/kg bdwt",
  "ng/ml", "uCI/g org", "ml/L", "g/kg"
)

conversion_factors <- c(
  1, 1e3, 1e3, 1, 1,
  1, NA, 1e3, 1e-3, NA,
  NA, NA, 1e3, NA, NA,
  1, NA, 1000, NA
)

# Remove NAs
unit_conversions.df <- data.frame(unit_names, conversion_factors) %>% filter(!is.na(conversion_factors))

cleaned_results <- tests.df %>%
  left_join(unit_conversions.df, by = join_by(conc1_unit == unit_names)) %>%
  mutate(conc1_mean = conc1_mean %>% as.numeric()) %>%
  relevant_cols()

cleaned_results.2 <- cleaned_results %>%
  mutate(conc_ug_L = conversion_factors * conc1_mean) %>% left_join(endpoint_classifications)# %>%

cleaned_results.3 <- cleaned_results.2 %>%
  rename(dose = conc_ug_L) %>% 
  distinct() %>% filter(!is.na(endpoint_type))
# join with taxonomy data

```

# Summarize available Data 

```{r}
chem_results <- chemicals %>% right_join(cleaned_results.3,by = join_by(test_cas))


results_summarized <- 
chem_results %>% 
group_by(epaName,ecotox_group,formatted_cas,effect,test_cas) %>% 
  summarize(
    #n=n(),
    no_types=n_distinct(endpoint_type)) %>% clipr::write_clip() %>% ungroup()

results_summarized %>% filter(no_types >=3) %>% dplyr::select(c(epaName,formatted_cas,test_cas))

```


Get first chemical 

```{r}
coc <- chemicals %>% 
  filter(epaName == "Acrolein")


```

Tests with this chemical 

```{r}

sel_tests <- cleaned_results.3 %>% filter(test_cas == coc$test_cas)%>% 
  left_join(endpoint_classifications) %>% 
  drop_empties()
  

model.1 <- drm(percent_val~(dose),data=sel_tests,
              fct=LL.2())

plot(model.1,main = coc$epaName,xlab = "dose ug/L",ylab = "response (percent mortality)")

model.1 %>% summary()

predict(model.1,data.frame(dose=log10(2)))
```



```{r}
 p1 <- ggplot(data = sel_tests, 
              aes(x = log10(dose), y = percent_val)) +
 geom_point() +
geom_smooth(method = "glm",
             method.args = list(family = binomial(link = "logit")), colour = "#FF0000", se = TRUE)

p1
```

```{r}
#try with random weights 

data.df <- sel_tests %>%
  mutate(weight = sample(1:30, size = n(), replace = TRUE))
 p2 <- ggplot(data = data.df, 
              aes(x = log10(dose), y = percent_val)) +
 geom_point() + 
geom_smooth(method = "glm", aes(weight = weight),
             method.args = list(family = binomial(link = "logit")), colour = "#FF0000", se = TRUE)

p2
```


